services:
  stackarr:
    build: .
    # image: ghcr.io/katalyst/stackarr:latest
    container_name: stackarr
    restart: unless-stopped
    ports:
      - "8484:8484"
    env_file: .env
    volumes:
      - ./config:/config
